name: Plugin asset/readme update
on:
  push:
    branches:
    - main
jobs:
  tag:
    name: Push to Main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Readme.txt
      run: curl -L https://raw.githubusercontent.com/reaktivstudios/wp-readme/master/wp-readme.php | php
    - name: WordPress.org plugin asset/readme update
      uses: 10up/action-wordpress-plugin-asset-update@master
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: screen-reader-text-format
